http://localhost:3000/personas

######################################

POST http://localhost:3000/personas HTTP/1.1
content-type: application/json

{
    "nombre": "margarita",
    "edad": 30
}

######################################

DELETE http://localhost:3000/personas/Juan1 HTTP/1.1

